# Generated by Django 3.2.15 on 2022-11-10 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0008_alter_post_songs'),
        ('users', '0001_initial'),
    ]

    operations = [

    ]
