# Generated by Django 3.2.15 on 2022-11-13 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0008_alter_post_songs'),
        ('music', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fave_songs',
            field=models.ManyToManyField(to='music.Song'),
        ),
        migrations.AddField(
            model_name='profile',
            name='joined_communities',
            field=models.ManyToManyField(to='groups.Community'),
        ),
    ]
