# Generated by Django 4.1.1 on 2022-11-06 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_remove_song_id_alter_song_song_id'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='songs',
            field=models.ManyToManyField(to='music.song'),
        ),
    ]
