# Generated by Django 3.2.15 on 2022-11-15 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20221113_0012'),
        ('users', '0002_profile_joined_communities'),
    ]

    operations = [
    ]
