# Generated by Django 3.2.15 on 2022-11-21 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_playlist'),
        ('users', '0003_merge_20221115_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='playlists',
            field=models.ManyToManyField(to='music.Playlist'),
        ),
    ]
