# Generated by Django 3.2.15 on 2022-11-30 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_playlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='playlist_creator',
            field=models.CharField(default='wooww', max_length=100),
            preserve_default=False,
        ),
    ]
