# Generated by Django 3.2.15 on 2022-11-08 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
        ('groups', '0007_auto_20221107_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='songs',
            field=models.ManyToManyField(blank=True, to='music.Song'),
        ),
    ]
