# Generated by Django 3.2.15 on 2022-12-03 20:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0008_alter_post_songs'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='raters',
            field=models.ManyToManyField(blank=True, related_name='post_requests_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
